name: wasteagram
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.16.0
  firebase_core : ^0.7.0
  firebase_storage: ^7.0.0
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1
  flutter:
    sdk: flutter
  location: ^3.0.0
  intl: ^0.16.1
  image_picker: ^0.6.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 
  integration_test:

flutter:

  uses-material-design: true
